caterwaul.module( 'factory' ,function($) {$.bbs_random=function( /* unary , node */seed) {;
return(function(it) {return(it.soft_type= 'rng' ) ,it} ) .call(this, ( (function( ) {var p=7243,q=8747,m=p*q;
return( (function(x) {return(x= (x|| (x=seed|| +new Date() %m) ) *x%m) /m} ) ) } ) .call(this) ) ) } ,$.factory= (function( ) {var should_be_rng=function( /* unary , node */x) {;
return(function(it) {return(x) } ) .call(this, ( ( ! (x&&x.soft_type=== 'rng' ) && ( (function( ) {throw( '' + (x) + ' should be a random number generator' ) } ) .call(this) ) ) ) ) } ,should_be_generator_or_constant=function( /* unary , node */x) {;
return(function(it) {return(x) } ) .call(this, ( ( ! ( !x||x.constructor!==Function||x.soft_type=== 'generator' ) && ( (function( ) {throw( '' + (x) + ' should be either a constant or a generator' ) } ) .call(this) ) ) ) ) } ,should_be_generator=function( /* unary , node */x) {;
return(function(it) {return(x) } ) .call(this, ( ( ! (x&&x.constructor===Function&&x.soft_type=== 'generator' ) && ( (function( ) {throw( '' + (x) + ' should be a generator' ) } ) .call(this) ) ) ) ) } ,generator=function(f,description) {;
return(function(it) {return(it.soft_type= 'generator' ,it.toString=function( /* unary , node */) {;
return description} ) ,it} ) .call(this, ( (function(r) {return should_be_rng(r) ,f.apply(this,arguments) } ) ) ) } ,array_generator_for=function( /* unary , node */xs) {;
return generator( (function(r) {return(function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x(r) ) ) ;
return xr} ) .call(this,xs) } ) , ( '[' + (xs.join( ", " ) ) + ']' ) ) } ,object_generator_for=function( /* unary , node */h) {;
return generator( (function(r) {return(function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x[0] ,x[1] (r) ] ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (h) ) ) ) ) } ) , ( '{' + ( (function(it) {return(it.join( ", " ) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x[0] + ": " +x[1] ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (h) ) ) ) ) ) + '}' ) ) } ,literally=function( /* unary , node */x) {;
return generator( (function(r) {return x} ) ,JSON.stringify(x) ) } ,promote_constants_in=function( /* unary , node */x) {;
return x?x.constructor===Array?array_generator_for( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (promote_constants_in(x) ) ) ;
return xr} ) .call(this,x) ) :x.constructor===Object?object_generator_for( (function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x[0] ,promote_constants_in(x[1] ) ] ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, (x) ) ) ) ) ) :x.constructor===Function?should_be_generator(x) :literally(x) :literally(x) } ,one_of=function() { /* unary ; node */var args=arguments;
return(function( ) {var xs= (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (promote_constants_in(x) ) ) ;
return xr} ) .call(this,Array.prototype.slice.call( (args) ) ) ;
return( (function(it) {return( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , (should_be_generator_or_constant(x) ) ;
return xs} ) .call(this,xs) ) ,it} ) .call(this, (generator( (function(r) {return xs[ (function(it) {return(console.log(it) ) ,it} ) .call(this, (r() ) ) *xs.length>>>0] (r) } ) , ( 'one_of(' + (xs.join( ", " ) ) + ')' ) ) ) ) ) } ) .call(this) } ,integer_between=function(x,y) {;
return generator( (function(r) {return r() * (y-x) +x>>>0} ) , ( 'integer between ' + (x) + ' and ' + (y) + '' ) ) } ,real_between=function(x,y) {;
return generator( (function(r) {return r() * (y-x) +x} ) , ( 'real between ' + (x) + ' and ' + (y) + '' ) ) } ;
return( (function(it) {return(it.one_of=one_of,it.integer_between=integer_between,it.literally=literally,it.real_between=real_between) ,it} ) .call(this, (promote_constants_in) ) ) } ) .call(this) } ) ;
